# Generated by Django 4.2.14 on 2025-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
