# Generated by Django 4.2.14 on 2025-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_student_is_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('not_updated', 'Not Updated')], default='not_updated', max_length=20),
        ),
    ]
