# Generated by Django 4.2.14 on 2025-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_student_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
